### PR TITLE
Changes to support SCO Unix 4.2 (SCO ODT) 

### PR DESCRIPTION
**Pull request by gattilorenz**
I added a few defines and an implementation for usleep, and it now works under SCO Unix 4.2.
However, since there's still a few C++ style comments in the code, it only compiles cleanly with GCC 2.7 (which I ended up releasing [here](https://github.com/gattilorenz/xenix-bins/tree/main/SCO%20ODT%203.0)).

Converting everything to pure C comments would let it compile right away with 2.5.8 and 2.6.3 too (available [here](https://archive.org/details/celestial-ftp-ports-for-unix), and probably more common and battle-tested than my 2.7).

### CODE REVIEW

**Comment by classilla** [comment]
Hey, thanks!

A couple things:
- This has a minor clash with the changes I just committed for the Mac OS MPW port. Can you rebase? Should be trivial.
- @larb0b , can you advise if this will be an issue for OpenServer, since you submitted that recipe?
- What C++ comments specifically? We should have purged all of those and the NeXTSTEP port in particular compiles fine with `gcc` 2.5.

Happy to take this with those questions addressed, and just in time, since I want to get a Cryanc checkpoint out (call it "2.2" this week or next).

**Comment by gattilorenz** [comment]
There's still C++ comments in lines 33370, 39791, 44016

**Comment by classilla** [comment]
Ah, thanks for spotting those. With those changes does it work on `gcc` 2.5.8 as well?

I pinged @larb0b in E-mail just in case he has any thoughts, since I don't have SCO or OpenServer locally.

**Comment by gattilorenz** [comment]
I just tested it with 2.6.3 and 2.5.8, and it works with both. I could probably test with OpenServer before next week, if needed.

**Comment by classilla** [comment]
Since it's going to take me a couple days to do all the build validation on the local systems, I'm going to go ahead and rubber stamp this. If you find it regresses OpenServer (or @larb0b does), please immediately submit a followup PR.

Thanks again!

**Comment by larb0b** [comment]
It still builds OK on OSR6 with GCC 7.3.

**Comment by classilla** [comment]
Excellent!

**Pull request merged**
