### PR TITLE
Add Haiku to the contributed section

### PR DESCRIPTION
**Pull request by larb0b**

### CODE REVIEW

**Comment by classilla** [comment]
My, aren't we on the ball! So it just works, with the `__BEOS__` define? I believe you, I'm just confirming.

**Comment by classilla** [comment]
(A single house-style nit: put backticks around x86_64, i.e., `x86_64`)

**Comment by larb0b** [comment]
It just hits the compiling for POSIX-SUS warning.

**Comment by classilla** [comment]
That's fine. Thanks.

**Pull request merged**
