### PR TITLE
Xenix version

### PR DESCRIPTION
**Pull request by gattilorenz**
Finally we got the Xenix version (which was my initial goal anyway, but it was easier to adapt it to SCO Unix first thanks to better documentation).

The only caveat I noticed so far is that under SCO Unix and Xenix `gethostbyname` doesn't work with ip addresses (it tries to resolve them and fails). I considered for a second copy-pasting and adapting `__nss_hostname_digits_dots_context` and write a wrapper around `gethostbyname`... but yeah, it's Xenix, who is going to care really?

### CODE REVIEW

**Comment by classilla** [comment]
Looks straightforward enough. What version of Xenix should this work with, and which compiler?

**Comment by classilla** [comment]
(and thank you!!)

**Comment by gattilorenz** [comment]
I tested it with Xenix 2.3.4 and gcc 2.5.8

**Comment by gattilorenz** [comment]
Without the unsupported `#warning` directives it compiles also under gcc-1.40... but you probably need to have the 2.5.8 distribution installed to have the correct headers to begin with, so that's useless anyway :)

**Comment by classilla** [comment]
Fair enough. I appreciate the port and I'll add it to the docs. Thanks again.

**Pull request merged**
